version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: berra
      POSTGRES_USER: berra
      POSTGRES_PASSWORD: berra
    ports:
      - '5432:5432'
    volumes:
      - local_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      APP_URL: http://localhost:3000
      JWT_SECRET: please-change-this-secret-value
      DATABASE_URL: postgresql://berra:berra@postgres:5432/berra
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - '4000:4000'

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: http://localhost:4000/api
    depends_on:
      - api
    ports:
      - '3000:3000'

volumes:
  local_postgres:
