version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: berra
      POSTGRES_USER: berra
      POSTGRES_PASSWORD: berra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U berra -d berra']
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      APP_URL: http://localhost:3000
      JWT_SECRET: change-me-in-staging
      DATABASE_URL: postgresql://berra:berra@postgres:5432/berra
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '4000:4000'

  worker:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    command: npm run worker
    environment:
      NODE_ENV: production
      JWT_SECRET: change-me-in-staging
      DATABASE_URL: postgresql://berra:berra@postgres:5432/berra
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: http://localhost:4000/api
    depends_on:
      - api
    ports:
      - '3000:3000'

volumes:
  postgres_data:
