[build]
  command = "npm install --ignore-scripts && cd apps/web && pnpm install && pnpm run build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions.___netlify-handler]
  included_files = [
    "apps/web/node_modules/styled-jsx/**/*",
    "node_modules/styled-jsx/**/*"
  ]

[functions.___netlify-odb-handler]
  included_files = [
    "apps/web/node_modules/styled-jsx/**/*",
    "node_modules/styled-jsx/**/*"
  ]
