[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix apps/api"]

[phases.build]
cmds = [
  "npm --prefix apps/api run prisma:generate",
  "npm --prefix apps/api run build"
]

[start]
cmd = "npm --prefix apps/api run start"
