[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @berra/api prisma:generate",
  "pnpm --filter @berra/api build"
]

[start]
cmd = "pnpm --filter @berra/api start"
