apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: araba-staging
  namespace: araba-staging
spec:
  ingressClassName: nginx
  rules:
    - host: staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: araba-web
                port:
                  number: 3000
    - host: api-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: araba-api
                port:
                  number: 4000
